
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: genrofeliz
  datasource:
    url: jdbc:postgresql://localhost:5432/genroFeliz
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db/migration

  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    port: 587
    username: gabrielsouzapequi@gmail.com
    password: svqh vvpk ryfz fwgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp
api:
  security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
logging:
  level:
    org.springframework.security: DEBUG
    org.h2: DEBUG