spring:
  application:
    name: genrofeliz
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:genrofeliz
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  h2:
    console:
      enabled: false
      path: /h2-console

  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    port: 587
    username: gabrielsouzapequi@gmail.com
    password: rqxj kilj blgk quoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp
api:
  security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
